import type { Player, Team } from "@/features/fpl";

/** Build a fully-typed Player for tests, overriding only what matters. */
export function makePlayer(overrides: Partial<Player> = {}): Player {
  const id = overrides.id ?? 1;
  return {
    id,
    code: 1000 + id,
    firstName: "Test",
    secondName: `Player ${id}`,
    webName: `Player ${id}`,
    fullName: `Test Player ${id}`,
    teamId: 1,
    teamCode: 3,
    teamName: "Test FC",
    teamShortName: "TST",
    positionId: 3,
    positionName: "Midfielder",
    positionShortName: "MID",
    availability: "available",
    news: "",
    chanceOfPlayingNextRound: null,
    photoUrl: "",
    price: {
      playerId: id,
      webName: `Player ${id}`,
      now: 5,
      nowRaw: 50,
      changeEvent: 0,
      changeStart: 0,
    },
    totalPoints: 50,
    eventPoints: 4,
    form: 4,
    pointsPerGame: 4,
    selectedByPercent: 10,
    minutes: 900,
    goalsScored: 3,
    assists: 3,
    cleanSheets: 3,
    goalsConceded: 8,
    ownGoals: 0,
    penaltiesSaved: 0,
    penaltiesMissed: 0,
    yellowCards: 1,
    redCards: 0,
    saves: 0,
    bonus: 5,
    bps: 200,
    starts: 10,
    influence: 400,
    creativity: 300,
    threat: 400,
    ictIndex: 110,
    expectedGoals: 3,
    expectedAssists: 3,
    expectedGoalInvolvements: 6,
    expectedGoalsConceded: 8,
    penaltiesOrder: null,
    cornersOrder: null,
    freeKicksOrder: null,
    transfersInEvent: 0,
    transfersOutEvent: 0,
    ...overrides,
  };
}

/** Build a fully-typed Team for tests. */
export function makeTeam(overrides: Partial<Team> = {}): Team {
  const id = overrides.id ?? 1;
  return {
    id,
    code: 3,
    name: `Team ${id}`,
    shortName: `T${id}`,
    strength: 3,
    played: 10,
    win: 5,
    draw: 2,
    loss: 3,
    points: 17,
    position: id,
    form: null,
    strengthOverallHome: 1150,
    strengthOverallAway: 1150,
    strengthAttackHome: 1150,
    strengthAttackAway: 1150,
    strengthDefenceHome: 1150,
    strengthDefenceAway: 1150,
    ...overrides,
  };
}
