export { DashboardPage } from "./DashboardPage";
export { TeamPage } from "./TeamPage";
export { AnalysePage } from "./AnalysePage";
export { SettingsPage } from "./SettingsPage";
export { NotFoundPage } from "./NotFoundPage";
export { RouteErrorPage } from "./RouteErrorPage";
export { DebugPage } from "./DebugPage";
export { PlayersPage } from "./PlayersPage";
export { SquadPage } from "./SquadPage";
